### ISSUE TITLE
'so-called' can be considered derogatory

### ISSUE THREAD

**Issue by hugobuddel** [astronomyk/ScopeSim-SPIE-paper#1]
The word 'so-called' can be interpreted derogatory, e.g. as in "The so-called experts said ...". Maybe you can rephrase the sentence below. Or maybe it is fine.

https://github.com/astronomyk/ScopeSim-SPIE-paper/blob/95c1216f14ae3810f0fab22f37238f35e81be28e/0_abstract.tex#L46

**Comment by astronomyk** [comment]
Thanks ;)
