### ISSUE TITLE
"Such simulation" should be "Such simulations"?

### ISSUE THREAD

**Issue by hugobuddel** [astronomyk/ScopeSim-SPIE-paper#5]
Or are you going for the Doge meme to cater to a younger audience? :dog:

https://github.com/astronomyk/ScopeSim-SPIE-paper/blob/0d13dd4ef77701856ed32de633b0c5f063465254/0_abstract.tex#L64

**Comment by astronomyk** [comment]
Such slimuation. Much Wow.
[Speaking of which, I wonder how much my 100 Dogecoins are now worth ... ¯\\_(ツ)_/¯  ]
